spring.application.name=spring-and-scim

# Logging
logging.level.web=debug
logging.level.sql=debug
logging.level.org.hibernate.orm.jbdc.bind=trace

# PostgreSQL-Datenbank
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=deinpasswort

# Hibernate-Einstellungen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.deserialization.accept-empty-string-as-null-object=true
